name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.19.0"

      - name: Install dependencies
        run: npm install

      - name: Build the Angular app
        run: npm run build --prod

      - name: Copy production files to deploy directory
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: dist/blog-pure-ng

      - name: Sleep for upload
        uses: jakejarvis/wait-action@master
        with:
          time: "6s"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/kivicko
            rm -rf * 
            git pull origin main

            # Download production artifact from previous step
            # wget https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}
            wget ${{ steps.artifact-upload-step.outputs.artifact-id }}

            unzip production-files.zip
            # Additional deployment commands (e.g., restart server process)
