name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.19.0"

      - name: Install dependencies
        run: npm install

      - name: Build the Angular app
        run: npm run build --prod

      - name: Copy production files to deploy directory
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: dist/blog-pure-ng

      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          local-dir: ./dist/blog-pure-ng/
          server-dir: /var/www/kivicko/
          dangerous-clean-slate: true

      - name: update permission
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/kivicko
            chown -R www-data:www-data *
            chmod -R 755 *
